# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZXSSdhMrssgKWvFPrhCMxn-6BUpVO-T_
"""

#@title <font color ="yellow">`⬅`</font><font color="#01c968">`Download from Link`</font>
#@markdown <font color ="red"><h6>`In "Firefox_cliget_wget_link" and "Firefox_Command_Line_Get_Curl_Link" method you can't edit Downloading file name using "File_Name" field`</h6>
def first4(s):
    return s[:4]
import os
Download_Link_Model = "Normal_Link" #@param ["Normal_Link", "Firefox_cliget_wget_link", "Firefox_Command_Line_Get_Curl_Link"] 

Download_Location = "" # @param {type:"string"}
if not Download_Location.strip():
  Download_Location = "/content"
from pathlib import Path
Path(Download_Location).mkdir(parents=True, exist_ok=True)
os.chdir(Download_Location)
Link = "" # @param {type:"string"}
File_Name = "" # @param {type:"string"}
if Download_Link_Model=="Firefox_cliget_wget_link":
  cliget_link = Link.strip()
  chk = first4(cliget_link)
  if chk=="wget":
    cliget_link = cliget_link[5:]  
  !wget -c $cliget_link --no-check-certificate
elif Download_Link_Model=="Firefox_Command_Line_Get_Curl_Link":
  CLG_Curl_Link = Link.strip()
  !$CLG_Curl_Link
else:
  if not File_Name.strip(): 
    !wget -c "$Link" --no-check-certificate
  else:  
    !wget -c "$Link" -O "$File_Name" --no-check-certificate